### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by bearkiter** [weltmeyer/ha_sonnenbatterie#10]
![image](https://user-images.githubusercontent.com/22023790/152073224-6f42510e-cb26-4bc6-94c7-7e565406d2fb.png)

Unable to complete setup.

Language pack issue?

**Comment by dge500** [comment]
I am having the same issue. I can log onto the battery via a web page.

**Comment by weltmeyer** [comment]
I have added english translations.
could you update and recheck?

**Comment by weltmeyer** [comment]
alright. so that was the missing english translation :)

**Comment by bearkiter** [comment]
Yep, fixed, now if Sonnen would get back to me about why I can't login any more I'd be good to go!!

Cheers
