### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by dge500** [weltmeyer/ha_sonnenbatterie#11]
The integration connected with my battery and I only have 1 entity which is the battery only.

I have no other entities. 

<img width="596" alt="HACS Info" src="https://user-images.githubusercontent.com/97660499/152513908-54409b92-2afd-4b14-86e2-446ac9ffd87a.png">

Below is the log file.

This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:173 
Integration: Sonnenbatterie (documentation) 
First occurred: 8:32:12 PM (282 occurrences) 
Last logged: 9:22:41 PM

Traceback (most recent call last): File "/config/custom_components/sonnenbatterie/sensor.py", line 159, in watcher self.updateData(); File "/config/custom_components/sonnenbatterie/sensor.py", line 145, in updateData self.latestData["inverter"]['status']=self.latestData["inverter"]['status']['status'] KeyError: 'status'

**Comment by weltmeyer** [comment]
which model do you have? it seems like it is missing some information in the api.

**Comment by dge500** [comment]
Battery: eco 8.2 AU 9010 ND
Software: 1.6.10
Firmware: 1.6.10.1174959

**Comment by dge500** [comment]
Great work. Thank you. I have updated and now have 39 entities.

I only have the below log error:

This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:149 
Integration: Sonnenbatterie (documentation) 
First occurred: 9:59:05 PM (60 occurrences) 
Last logged: 10:09:42 PM

Traceback (most recent call last): File "/config/custom_components/sonnenbatterie/sensor.py", line 146, in updateData self.latestData["inverter"]['status']=self.latestData["inverter"]['status']['status'] KeyError: 'status'

**Comment by weltmeyer** [comment]
it should also show one error once for line 2XX. can you see it?

**Comment by dge500** [comment]
I have fully restarted HA and I have had the following errors:

This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:149 
Integration: Sonnenbatterie (documentation) 
First occurred: 10:19:03 PM (10 occurrences) 
Last logged: 10:20:41 PM

Traceback (most recent call last): File "/config/custom_components/sonnenbatterie/sensor.py", line 146, in updateData self.latestData["inverter"]['status']=self.latestData["inverter"]['status']['status'] KeyError: 'status'

This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:267 
Integration: Sonnenbatterie (documentation) 
First occurred: 10:19:03 PM (1 occurrences) 
Last logged: 10:19:03 PM

{'status': {'acloadsactivepower': '8', 'acloadscosphi': '997', 'acloadscurrent': '18', 'acloadsfrequency': '5001', 'acloadsreactivepower': '65491', 'acloadsvoltage': '246', 'activepowerreductionratio': '230', 'activepowerreductionreason': '1', 'batterycurrent': '1461', 'batterymaxchargingcurrent': '799', 'batterymaxdischargingcurrent': '4995', 'batterypower': '731', 'batterysoc': '49', 'batterysoh': '100', 'batterystatus': '1', 'batterytemperature': '0', 'batteryvoltage': '502', 'dailyenergyconsumedbytheloads': '0', 'dailyenergydeliveredbypv': '0', 'dailyenergydeliveredbythebattery': '1000', 'dailyenergyinjectedtothegrid': '0', 'dailyenergystoredinthebattery': '400', 'day': '4', 'dcbusvoltage': '356', 'digitalinput1': '0', 'digitaloutput1': '1', 'digitaloutput2': '0', 'externalwattmeteractivepower': '0', 'externalwattmeterreactivepower': '0', 'gridgensetactivepower': '664', 'gridgensetcurrent': '275', 'gridgensetfrequency': '5000', 'gridgensetreactivepower': '65532', 'gridgensetvoltage': '246', 'hour': '12', 'inverteracphaseconfig': '0', 'inverteractivepower': '672', 'inverteralarms': '0x01', 'invertercode1': '0x00', 'invertercode2': '0x80', 'inverterreactivepower': '65487', 'inverterstatusflag': '11', 'minute': '30', 'month': '2', 'negativeisolationresistence': '17557', 'positiveisolationresistence': '4115', 'pvcurrent': '0', 'pvpower': '0', 'pvvoltage': '356', 'reactivepowersetpointtype': '0', 'second': '35', 'selfconsumptionratio': '4', 'temperatureheatsink': '619', 'temperatureic': '619', 'temperaturept100': '65336', 'totaloperationhours': '8285', 'year': '2022'}, 'settings': {'common': {'Grid Nominal Values': {'Nominal Grid Frequency': '50.00', 'Nominal Grid Voltage': '230.00'}, 'Threshold Values': {'Charge Threshold': 'nan', 'Discharge Threshold': 'nan'}}, 'cosphiconfiguration': {'cosphienable': False, 'login_pac': '50', 'logout_pac': '1000', 'phipoint1': '1000', 'phipoint2': '1000', 'phipoint3': '1000', 'phipoint4': '1000', 'phipoint5': '1000', 'ppoint1': '0', 'ppoint2': '25', 'ppoint3': '50', 'ppoint4': '75', 'ppoint5': '100'}, 'deviceinfo': {'display_fw_boot_version': '', 'display_fw_version': '', 'firwmware_version': 'ABH1002_X', 'fw_boot_version': 'ABH1010_ ', 'run_indicator_status': '0xF0', 'serial_number': 'E00020296251', 'slave_id': 0, 'string_kit_code': 0, 'unit_flag': 0}, 'holdingregisters': {'absorptionvoltage': '72', 'auxiliarygeneratorratedpower': '3500', 'baudratecan': '500', 'boostcurrentscalefactor': '15007', 'boostvoltagescalefactor': '653', 'capacity': '175', 'capacity2': '151', 'countrycodeandregulation': 'RD+UNE206007_Peninsular', 'day': '4', 'dcstartvoltage': '0', 'dcstopvoltage': '0', 'digitalinput': '0', 'digitaloutput1': '9', 'digitaloutput2': '0', 'digitaloutputhighbattvoltage': '60', 'digitaloutputlowbattvoltage': '45', 'displaylanguage': '1', 'durationofabsorptioncharge': '20', 'durationofequalizationcharge': '60', 'equalizationvoltage': '78', 'flotationvoltage': '69', 'frequencyofgeneratedvoltage': '50', 'gridcurrentscalefactor': '22260', 'gridfrequencyh1limit': '100', 'gridfrequencyh1time': '50', 'gridfrequencyh2limit': '500', 'gridfrequencyh2time': '50', 'gridfrequencyl1limit': '65336', 'gridfrequencyl1time': '304', 'gridfrequencyl2limit': '64736', 'gridfrequencyl2time': '304', 'gridvoltageh1limit': '1100', 'gridvoltageh1time': '1500', 'gridvoltageh2limit': '1150', 'gridvoltageh2time': '200', 'gridvoltagehavgvlimit': '1350', 'gridvoltagel1limit': '850', 'gridvoltagel1time': '1500', 'gridvoltagel2limit': '0', 'gridvoltagel2time': '1500', 'gridvoltagescalefactor': '1093', 'hour': '12', 'insulationdcimpedance': '19', 'inverteracmaxcurrent': '1350', 'inverteracmaxpower': '3000', 'inverteracnominalpower': '3000', 'invertercurrentscalefactor': '5551', 'inverterflags_1': '33', 'inverterflags_2': '1556', 'invertervoltagescalefactor': '1099', 'maxacfreqofthegenerator': '65', 'maxacvoltageofthegenerator': '250', 'maxbattchargingpower': '0', 'maxchargecurrent': '50', 'maxdischargecurrent': '50', 'maxpowerinjectedintogrid': '0', 'maxvoltagecell': '26214', 'minacfreqofthegenerator': '45', 'minacvoltageofthegenerator': '190', 'minute': '30', 'minvoltage': '57', 'modbuscomtimeout': '10000', 'monitoringtimeofdatalogger': '15', 'month': '2', 'nominal grid frequency': '5000', 'nominal grid voltage': '23000', 'nominalvoltage': '60', 'numberofcyclestocarryoutautoequalization': '0', 'phasetobegeneratedvoltage': '0', 'pvreferencevoltage': '400', 'pvsflockintimeabsorbed': '1000', 'pvsflockintimeinjected': '1000', 'referencecosphi': '1000', 'referencesignsinphi': '0', 'rmsvoltagegenerated': '230', 'second': '22', 'socdescx': '60', 'socgrid': '0', 'socmax': '100', 'socmin': '0', 'socrecx': '50', 'strategyoftheinverter': '1', 'time1offhour': '8', 'time1offminute': '0', 'time1onhour': '0', 'time1onminute': '0', 'time2offhour': '11500', 'time2offminute': '0', 'time2onhour': '10', 'time2onminute': '0', 'time3offhour': '0', 'time3offminute': '0', 'time3onhour': '0', 'time3onminute': '0', 'transformerconfiguration': '4', 'typeofbattery': '8', 'typeofgrid': '1', 'voltagecompensationconstant': '4', 'waitingtimetoconnect': '0', 'year': '2022'}, 'qvsuconfiguration': {'loginpac': '50', 'logoutpac': '1000', 'qpoint1': '0', 'qpoint2': '0', 'qpoint3': '0', 'qpoint4': '0', 'qpoint5': '0', 'qvsuenable': '0', 'vpoint1': '0', 'vpoint2': '0', 'vpoint3': '0', 'vpoint4': '0', 'vpoint5': '0'}}}

This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:266 
Integration: Sonnenbatterie (documentation) 
First occurred: 10:19:03 PM (1 occurrences) 
Last logged: 10:19:03 PM

Traceback (most recent call last): File "/config/custom_components/sonnenbatterie/sensor.py", line 258, in AddOrUpdateEntities val=inverter['status']['ppv'] KeyError: 'ppv'

This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:254 
Integration: Sonnenbatterie (documentation) 
First occurred: 10:19:03 PM (1 occurrences) 
Last logged: 10:19:03 PM

{'status': {'acloadsactivepower': '8', 'acloadscosphi': '997', 'acloadscurrent': '18', 'acloadsfrequency': '5001', 'acloadsreactivepower': '65491', 'acloadsvoltage': '246', 'activepowerreductionratio': '230', 'activepowerreductionreason': '1', 'batterycurrent': '1461', 'batterymaxchargingcurrent': '799', 'batterymaxdischargingcurrent': '4995', 'batterypower': '731', 'batterysoc': '49', 'batterysoh': '100', 'batterystatus': '1', 'batterytemperature': '0', 'batteryvoltage': '502', 'dailyenergyconsumedbytheloads': '0', 'dailyenergydeliveredbypv': '0', 'dailyenergydeliveredbythebattery': '1000', 'dailyenergyinjectedtothegrid': '0', 'dailyenergystoredinthebattery': '400', 'day': '4', 'dcbusvoltage': '356', 'digitalinput1': '0', 'digitaloutput1': '1', 'digitaloutput2': '0', 'externalwattmeteractivepower': '0', 'externalwattmeterreactivepower': '0', 'gridgensetactivepower': '664', 'gridgensetcurrent': '275', 'gridgensetfrequency': '5000', 'gridgensetreactivepower': '65532', 'gridgensetvoltage': '246', 'hour': '12', 'inverteracphaseconfig': '0', 'inverteractivepower': '672', 'inverteralarms': '0x01', 'invertercode1': '0x00', 'invertercode2': '0x80', 'inverterreactivepower': '65487', 'inverterstatusflag': '11', 'minute': '30', 'month': '2', 'negativeisolationresistence': '17557', 'positiveisolationresistence': '4115', 'pvcurrent': '0', 'pvpower': '0', 'pvvoltage': '356', 'reactivepowersetpointtype': '0', 'second': '35', 'selfconsumptionratio': '4', 'temperatureheatsink': '619', 'temperatureic': '619', 'temperaturept100': '65336', 'totaloperationhours': '8285', 'year': '2022'}, 'settings': {'common': {'Grid Nominal Values': {'Nominal Grid Frequency': '50.00', 'Nominal Grid Voltage': '230.00'}, 'Threshold Values': {'Charge Threshold': 'nan', 'Discharge Threshold': 'nan'}}, 'cosphiconfiguration': {'cosphienable': False, 'login_pac': '50', 'logout_pac': '1000', 'phipoint1': '1000', 'phipoint2': '1000', 'phipoint3': '1000', 'phipoint4': '1000', 'phipoint5': '1000', 'ppoint1': '0', 'ppoint2': '25', 'ppoint3': '50', 'ppoint4': '75', 'ppoint5': '100'}, 'deviceinfo': {'display_fw_boot_version': '', 'display_fw_version': '', 'firwmware_version': 'ABH1002_X', 'fw_boot_version': 'ABH1010_ ', 'run_indicator_status': '0xF0', 'serial_number': 'E00020296251', 'slave_id': 0, 'string_kit_code': 0, 'unit_flag': 0}, 'holdingregisters': {'absorptionvoltage': '72', 'auxiliarygeneratorratedpower': '3500', 'baudratecan': '500', 'boostcurrentscalefactor': '15007', 'boostvoltagescalefactor': '653', 'capacity': '175', 'capacity2': '151', 'countrycodeandregulation': 'RD+UNE206007_Peninsular', 'day': '4', 'dcstartvoltage': '0', 'dcstopvoltage': '0', 'digitalinput': '0', 'digitaloutput1': '9', 'digitaloutput2': '0', 'digitaloutputhighbattvoltage': '60', 'digitaloutputlowbattvoltage': '45', 'displaylanguage': '1', 'durationofabsorptioncharge': '20', 'durationofequalizationcharge': '60', 'equalizationvoltage': '78', 'flotationvoltage': '69', 'frequencyofgeneratedvoltage': '50', 'gridcurrentscalefactor': '22260', 'gridfrequencyh1limit': '100', 'gridfrequencyh1time': '50', 'gridfrequencyh2limit': '500', 'gridfrequencyh2time': '50', 'gridfrequencyl1limit': '65336', 'gridfrequencyl1time': '304', 'gridfrequencyl2limit': '64736', 'gridfrequencyl2time': '304', 'gridvoltageh1limit': '1100', 'gridvoltageh1time': '1500', 'gridvoltageh2limit': '1150', 'gridvoltageh2time': '200', 'gridvoltagehavgvlimit': '1350', 'gridvoltagel1limit': '850', 'gridvoltagel1time': '1500', 'gridvoltagel2limit': '0', 'gridvoltagel2time': '1500', 'gridvoltagescalefactor': '1093', 'hour': '12', 'insulationdcimpedance': '19', 'inverteracmaxcurrent': '1350', 'inverteracmaxpower': '3000', 'inverteracnominalpower': '3000', 'invertercurrentscalefactor': '5551', 'inverterflags_1': '33', 'inverterflags_2': '1556', 'invertervoltagescalefactor': '1099', 'maxacfreqofthegenerator': '65', 'maxacvoltageofthegenerator': '250', 'maxbattchargingpower': '0', 'maxchargecurrent': '50', 'maxdischargecurrent': '50', 'maxpowerinjectedintogrid': '0', 'maxvoltagecell': '26214', 'minacfreqofthegenerator': '45', 'minacvoltageofthegenerator': '190', 'minute': '30', 'minvoltage': '57', 'modbuscomtimeout': '10000', 'monitoringtimeofdatalogger': '15', 'month': '2', 'nominal grid frequency': '5000', 'nominal grid voltage': '23000', 'nominalvoltage': '60', 'numberofcyclestocarryoutautoequalization': '0', 'phasetobegeneratedvoltage': '0', 'pvreferencevoltage': '400', 'pvsflockintimeabsorbed': '1000', 'pvsflockintimeinjected': '1000', 'referencecosphi': '1000', 'referencesignsinphi': '0', 'rmsvoltagegenerated': '230', 'second': '22', 'socdescx': '60', 'socgrid': '0', 'socmax': '100', 'socmin': '0', 'socrecx': '50', 'strategyoftheinverter': '1', 'time1offhour': '8', 'time1offminute': '0', 'time1onhour': '0', 'time1onminute': '0', 'time2offhour': '11500', 'time2offminute': '0', 'time2onhour': '10', 'time2onminute': '0', 'time3offhour': '0', 'time3offminute': '0', 'time3onhour': '0', 'time3onminute': '0', 'transformerconfiguration': '4', 'typeofbattery': '8', 'typeofgrid': '1', 'voltagecompensationconstant': '4', 'waitingtimetoconnect': '0', 'year': '2022'}, 'qvsuconfiguration': {'loginpac': '50', 'logoutpac': '1000', 'qpoint1': '0', 'qpoint2': '0', 'qpoint3': '0', 'qpoint4': '0', 'qpoint5': '0', 'qvsuenable': '0', 'vpoint1': '0', 'vpoint2': '0', 'vpoint3': '0', 'vpoint4': '0', 'vpoint5': '0'}}}

This error originated from a custom integration.

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:253 
Integration: Sonnenbatterie (documentation) 
First occurred: 10:19:03 PM (1 occurrences) 
Last logged: 10:19:03 PM

Traceback (most recent call last): File "/config/custom_components/sonnenbatterie/sensor.py", line 245, in AddOrUpdateEntities val=inverter['status']['fac'] KeyError: 'fac'

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:96 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 10:18:59 PM (4 occurrences) 
Last logged: 10:18:59 PM

[547687698736] Received invalid command: energy/get_prefs

**Comment by weltmeyer** [comment]
this should be fixed in the latest version. The error should pop once, but all other sensors should work fine.
