### ISSUE TITLE
Type of entity classes does not match the value

### ISSUE THREAD

**Issue by marcorizzi** [weltmeyer/ha_sonnenbatterie#12]
The unit of your entity is not a supported unit for the device class of the entity, power.
Statistics can not be generated until this entity has a supported unit.

If this unit was provided by an integration, this is a bug. Please report an issue.

If you have set this unit yourself, and want to have statistics generated, make sure the unit matches the device class. The supported units are documented in the [developer documentation](https://developers.home-assistant.io/docs/core/entity/sensor/#available-device-classes).

Some example are **Charge Percentage User/Real** that has 'power' class with unit % and need to changed to 'battery'

**Comment by weltmeyer** [comment]
this should be fixed with the latest version, can you confirm?

**Comment by marcorizzi** [comment]
well done! Updated. Do you think that also Battery Charging Power (in and out) needs to be updated to battery device class ?

**Comment by weltmeyer** [comment]
as per the developer doc, battery only allows % as a unit of measure. i dont see how i could put in/out power in percentage here...
![image](https://user-images.githubusercontent.com/1668465/162473784-a02fce5b-68ee-41e4-9e60-aeb9c8723c91.png)

**Comment by marcorizzi** [comment]
You are right. Good!
