### ISSUE TITLE
New Energy dashboard does not support sonnen sensors

### ISSUE THREAD

**Issue by marcorizzi** [weltmeyer/ha_sonnenbatterie#13]
Why the new Energy dashboard of HA does not support Sonnen sensors in term of 'no sensors available on the dropdown of the energy configuration' to select sensors for In/Out grid, solar production and battery system ?

**Comment by weltmeyer** [comment]
Energy Dashboard only shows energy, not power(which are the sensors from sonnen)

**Comment by weltmeyer** [comment]
i added some documentation in the wiki
