### ISSUE TITLE
Rendering of historic sensor values broken in 2022.04

### ISSUE THREAD

**Issue by alsFC** [weltmeyer/ha_sonnenbatterie#15]
With the current 2022.04 Release the default rendering of history graphs of the sensors changed to bar charts. Probably defining of **device_class** and **unit_of_measurement** attributes for all sensors will solve the problem.

![image](https://user-images.githubusercontent.com/14979356/162143943-60debea2-9102-43f1-9b2f-1675fafefc8f.png)

**Comment by alsFC** [comment]
also **state_class** attribute would be nice to support system-native long term statistics.

**Comment by geni0602** [comment]
Hi, 
Same for me with the new update 2022.4. units of measurement are not available and no more history graph.
It will be nice, if you could fix it.

Thanks!

**Comment by weltmeyer** [comment]
Didnt mean to close it directly before you also confirm this works with the latest update :)
Can you check please?

**Comment by geni0602** [comment]
It´s looking good. Units of measurement are fine and the graphs as well.

Thanks a lot!

**Comment by alsFC** [comment]
All the sensors looking good now! 🙂
Thank you!

One thing: the actual state of the battery (charging, discharging, etc.) renders as graph now. Perhaps because **unit_of_measurement** and **device_class** are defined for this sensor as well but are set to **none**.

**Comment by weltmeyer** [comment]
> All the sensors looking good now! 🙂 Thank you!
> 
> One thing: the actual state of the battery (charging, discharging, etc.) renders as graph now. Perhaps because **unit_of_measurement** and **device_class** are defined for this sensor as well but are set to **none**.

Should also be fixed with another update, thanks for reporting.

i am closing this now
