### ISSUE TITLE
device_class maybe missing?

### ISSUE THREAD

**Issue by WLammert** [weltmeyer/ha_sonnenbatterie#16]
It is not possible to add the battery sensors to the energy dashboard "Batteriespeicher zu Hause". They just don't appear in the selection. I don't know the reason but maybe the device_class parameters are set incorrectly? Just a guess...
Anyways it would be very benefitial if the battery stats could be imported into the energy dashboard.

Thanks in advance!

**Comment by weltmeyer** [comment]
https://github.com/weltmeyer/ha_sonnenbatterie/wiki#energy-dashboard there also is a pinned issue already on top of the issues...
