### ISSUE TITLE
Wrong Capacity

### ISSUE THREAD

**Issue by Lumex91** [weltmeyer/ha_sonnenbatterie#18]
Hello I have a SonnenBatterie 10 (with 11kW),

but the sensor only show me a capacity from 4800 W

di i do something wrong?

Modell: power unit sB10s sI1 9010 IP30 sDCM
Firmware is 1.6.18

Can you help me?
Thank you

**Comment by weltmeyer** [comment]
Are the other values correct?
How many battery modules do you have?
can you confirm, that you have 4 modules?

**Comment by Lumex91** [comment]
Hello,

All values within the capacity are wrong
I have 2 modules each 5,5 kw

**Comment by weltmeyer** [comment]
Alright, can you try with the latest update. it should 
a) output more correct data for total wattage and remaining capacity
b) add sensors for module count and capacity per module

**Comment by Lumex91** [comment]
Thank you very much... now all values are right

**Comment by alsFC** [comment]
Vielen Dank! Habe eine Batterie mit gleichen Parametern und nun auch alles korrekt in Home Assistant 😀

**Comment by rcruikshank** [comment]
I think you are mixing up two different things. The battery capacity is
probably 11kWh capacity of storage and capable of 4.8 kW (not kWh)
discharge rate. Two different things.

An 11kWh battery with 4.8 kW capacity would take 11/4.8=2.3 hours to
completely discharge if drained at its full rate.
