### ISSUE TITLE
PPV2 values?

### ISSUE THREAD

**Issue by jepperc** [weltmeyer/ha_sonnenbatterie#19]
Can the api this integration calls get the PPV2 values? After losing access to the installer section(Sonnen upgrade) i can't get readings for the secondary ppv in the ui. But it looks like the api here returns it, just doesn't populate sensor values?

**Comment by weltmeyer** [comment]
Do you know where in the api the value is returned?

**Comment by jepperc** [comment]
It could just be called PPV2 here?
https://github.com/weltmeyer/ha_sonnenbatterie/blob/78d8a6a602e35a66574c510507fa68ade7fbc369/custom_components/sonnenbatterie/sensor.py#L291
In the old interface (http://sonnenbattery:8080) you could login with installer and see this exact value. Since this is the old API i would guess the same value would be there.

**Comment by xlibbyx** [comment]
I would also be interested in the PPV2 value. Is it possible to add myself?

**Comment by KlavsKlavsen** [comment]
Here's a discussion on how someone improved upon this - to use apiV2
Hopefully this could be integrated into this plugin - to make it much easier to use.
https://community.home-assistant.io/t/sonnenbatterie-with-apiv2-webhook/264907

**Comment by jepperc** [comment]
How would that help anything? It doesn't have PPV2 values 😬

tor. 15. dec. 2022 16.29 skrev Klavs Klavsen ***@***.***>:

**Comment by KlavsKlavsen** [comment]
the ppv2 values aren't in the new API output on your system?

**Comment by weltmeyer** [comment]
as i dont have an inverter, i cant check for these ppv values. i blindly added ppv2 now. can you try latest master?

**Comment by jepperc** [comment]
No.. and it's not in the screenshots in the link you provided either. There is not PPV1 either.. only Production_W which is the combined.

**Comment by jepperc** [comment]
> as i dont have an inverter, i cant check for these ppv values. i blindly added ppv2 now. can you try latest master?

Will try tonight when I get my new HA server up and running :)

**Comment by xlibbyx** [comment]
> as i dont have an inverter, i cant check for these ppv values. i blindly added ppv2 now. can you try latest master?

Thanks for this. I have updated and added PP2 to my frontend so I will report back when the sun is up tomorrow.

**Comment by xlibbyx** [comment]
![ppv](https://user-images.githubusercontent.com/24729381/208055223-dc0684e0-3ffe-4e92-bf4f-ea877738da4a.png)

Looks like it worked!

**Comment by weltmeyer** [comment]
nice. gonna close this ticket.

**Comment by jepperc** [comment]
Works great :) Thank you!
