### ISSUE TITLE
Reading of temperature

### ISSUE THREAD

**Issue by Thohacat** [weltmeyer/ha_sonnenbatterie#20]
Hi,

I am using a sonnenbatterie 8.0 and i would like to display the inside temperature of the battery. Acc. to sonnen service that is possible by using API. Does anyone realized it?

Thanks for a short feedback.

**Comment by weltmeyer** [comment]
I added the tmax value as a sensor in the latest commit #21 e7f5081828b69d534b1b931d9cc0ec6f8a253e16

**Comment by Thohacat** [comment]
That's great. Thanks! I impleted this new parameter and i know in my room is around 15°. The new implemented temperature shows me 27,99°C. I expected this should be close to my room temperature. Do we have more than one temperature device or parameter? I ask it because you named it tmax. Thanks for a short feedback.

**Comment by weltmeyer** [comment]
I cant find any other temperatures in the API, it looks like its measuring inside the device.

**Comment by Thohacat** [comment]
Ok, let's see how it works. I can see following difference: Room temperature around 10°C and is changing in dependence of outside temperature (battery is located inside of a garage, isolated). Your tmax. shows me constant value around 27°C. I will check it for a period of time. Thanks!
