### ISSUE TITLE
integration sonnenbatterie broken on 2021.5.4

### ISSUE THREAD

**Issue by robertovendrame** [weltmeyer/ha_sonnenbatterie#3]
I enter the correct data of sonnenbatterie , but nothing happens, and I find this error in the log

On: core-2021.5.4

![image](https://user-images.githubusercontent.com/62454469/119472919-f32d6480-bd4a-11eb-8da1-b3f5aefea01b.png)

**Comment by weltmeyer** [comment]
fixed with latest commit. Please try with the latest Version from Git
