### ISSUE TITLE
Sensor reading total production 

### ISSUE THREAD

**Issue by PySmurf** [weltmeyer/ha_sonnenbatterie#34]
Hi,
There is differences in the read-out of the total production and that Sonnen shows in the app.

When adding the other sensors together (consumption, battery and grid) these dosen't add up the the read-out of productions sensor, but confirm the number that can be read-out in Sonnen App.

Br PySmurf
![image](https://user-images.githubusercontent.com/112606245/236607570-c311dfa7-9408-440c-9fcd-c3a23f7b0d3b.png)

![image](https://user-images.githubusercontent.com/112606245/236607680-284b099a-37c1-42c0-9d73-3de1f4e12572.png)

**Comment by weltmeyer** [comment]
Hi,
can you check the values, that are shown on the batterie itself? 
For this, you can open the IP of your battery in the browser and login as User with password sonnenuser3552.

**Comment by PySmurf** [comment]
That seems correct

![image](https://user-images.githubusercontent.com/112606245/236612398-db769a34-0480-4b54-88ec-a5ab9b340e39.png)

**Comment by PySmurf** [comment]
Comparison of production

![image](https://user-images.githubusercontent.com/112606245/236612447-a8efc1de-7fc4-481a-aea1-38efe44845d8.png)

**Comment by PySmurf** [comment]
Comparison of consumption from grid
![image](https://user-images.githubusercontent.com/112606245/236612520-96dd0271-49a8-420e-9950-480d2ac322a4.png)

**Comment by PySmurf** [comment]
And a comparison of total consumption

![image](https://user-images.githubusercontent.com/112606245/236612559-dc412519-58c2-4d22-9766-ef9d35bbcb75.png)

**Comment by weltmeyer** [comment]
I added a new sensor, can you update the integration and check the production_w sensor?
Also, for it looks strange that you have Consumption on the Grid, while i have "FeedIn" 
Do you have a SonnenFlat or something?

**Comment by PySmurf** [comment]
Hi
The 2 new sensors seems correct. Yay, I have wondered by this consumption from grid, it is a small consumption, so I think it is because the inverter in battery not is accurate / fast enough.

I have 12.5 KWH sonnen battery with a additional huawei inverter, maybe this is what causing some lack.

Thanks

![image](https://user-images.githubusercontent.com/112606245/236613793-7fe3c4ac-b997-4279-ad98-28ffa002fbaf.png)

**Comment by weltmeyer** [comment]
I only have a small difference between the total sensor and the production_w sensor. always around 1-10W. 
If i have some time, i need to check which one of these are closer to the values from my inverter :)
