### ISSUE TITLE
I cannot re-install integration

### ISSUE THREAD

**Issue by WW2101** [weltmeyer/ha_sonnenbatterie#35]
I had some issues with the integration and decided to do a re-install.

Now it seems I can no longer find my battery on my network?

https://find-my.sonnen-batterie.com/ provides 172.16.172.14 as IP but I this does not seem as a valid IP address (I cannot find u via my router) and when I click on Assistant 2.0 the page does not load...

Anybody knows how to fix this issue so I can add my battery back to Home Assistant..?

Thanks in advance!

**Comment by weltmeyer** [comment]
172.16.172.14 is basically a valid IP address. Its just not often used in private networks. if you cant find the sonnenbatterie in your router then there must be something strange going on with you battery. could you try to unplug, wait 10 seconds, then replug the LAN-Cable of the battery? This way it should get a new DHCP lease from your router. I am asuming a basic and simple router with integrated DHCP here.

**Comment by weltmeyer** [comment]
Also, what happens if you open 172.16.172.14  in a browser?

**Comment by WW2101** [comment]
> 

Nothing, screen remains white...

**Comment by WW2101** [comment]
> 172.16.172.14 is basically a valid IP address. Its just not often used in private networks. if you cant find the sonnenbatterie in your router then there must be something strange going on with you battery. could you try to unplug, wait 10 seconds, then replug the LAN-Cable of the battery? This way it should get a new DHCP lease from your router. I am asuming a basic and simple router with integrated DHCP here.

I did not know it was a valid IP.
I wanted to avoid unplugging as the battery is also managed by a third party (installer, for purposes of dynamic energy contract and balance market). 
Thanks for the assistance!

**Comment by weltmeyer** [comment]
It maybe that your battery is offline by now.. also a replug is then nearly the same as if you restart your router.. should not be a problem.

**Comment by WW2101** [comment]
Sonnen app worked fine the whole time though...

**Comment by WW2101** [comment]
Unplugging did not appear to have worked... IP address is still the same, still nothing when I want to connect to Assistant 2.0...

**Comment by weltmeyer** [comment]
- Do you have any backup where the battery was still working in Home Assistant? You might extract the IP address from there.
- If not you can still scan your network for your battery(using a local ip scanner of your choice)
- If you battery is working in the sonnenapp then its traffic should also go through your router and its should be listed there as an active client(FritzBox for example should show it on the "Home Network" page)
