### ISSUE TITLE
Can't find this integration in the HACS addon

### ISSUE THREAD

**Issue by CarstenDennis** [weltmeyer/ha_sonnenbatterie#36]
Hi

I want to install the integration, and I followed the guide here to get HACS installed
https://hacs.xyz/docs/setup/prerequisites

However I can't find it in HACS, am I doing something wrong?

This is what I see:
![image](https://github.com/weltmeyer/ha_sonnenbatterie/assets/139639309/e3422dfa-6fa9-4270-a0f0-acf1dbaed21f)

Also looked under HA_sonnenbattery - but nothing there as well

Thanks in advance!

**Comment by RustyDust** [comment]
In your HA installation go to

`HACS` -> `Integrations` 

Click on the three vertical dots in the upper right corner and choose `Custom repositories`
In the `Repository` input field, enter the URL of this repo, e.g. `https://github.com/weltmeyer/ha_sonnenbatterie`

**Comment by CarstenDennis** [comment]
Doh

Many thanks - that solved it :-)
