### ISSUE TITLE
Not available in HACS

### ISSUE THREAD

**Issue by Jelleverley** [weltmeyer/ha_sonnenbatterie#4]
I’m trying to install the repository via HACS.
I can’t find it in the list of integrations.

**Comment by rcruikshank** [comment]
You don't install from the list of integrations in HACS. You install from Github. 
Select 'Explore and add repository' and enter 'https://github.com/weltmeyer/ha_sonnenbatterie' into 'search for reporitory'.

**Comment by Jelleverley** [comment]
Ok!
Now I have it installed in HACS.
But didn’t get the configuration screen to set the parameters.
I also tried to install it via configuration/integrations but it’s not available in the list of integrations


Verstuurd vanaf mijn iPhone

**Comment by rcruikshank** [comment]
I think if you've installed it correctly it should be available in
"configuration", "Integrations".
Just select Configuration from the main HA menu (not HACS) then select
Integrations, then "+ Add Integrations", then in the in the "Search
Integrations" field type sonnenbatteries and it will come up. When you add
it, it should ask for IP address etc.

**Comment by Jelleverley** [comment]
Ok it works!
