### ISSUE TITLE
Change IP

### ISSUE THREAD

**Issue by n3de** [weltmeyer/ha_sonnenbatterie#41]
Hey, how can I change the IP address of the Sonnenbatterie? I can't find any config...

**Comment by n3de** [comment]
@weltmeyer any idea?

**Comment by weltmeyer** [comment]
Just login to you battery, got to network and set the ip to static should work.
<img width="903" alt="image" src="https://github.com/weltmeyer/ha_sonnenbatterie/assets/1668465/3d1f7675-798c-487a-b199-dddd8fdb336a">

It may be a better idea to set a static lease within your DHCP-Server settings...

**Comment by n3de** [comment]
Thanks @weltmeyer  for the fast reply, but I'm using static dhcp. I changed my whole network and the battery is in a different sub net now. I want to change the ip in homeassistant so everything will work like before.

**Comment by weltmeyer** [comment]
ahh just remove the current configuration and readd it with the new ip address.
the integration is using the serialnumber of the battery so all sensor id's should stay the same.
