### ISSUE TITLE
Sensor Not set

### ISSUE THREAD

**Issue by gerrit59** [weltmeyer/ha_sonnenbatterie#42]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:135
Integration: Sonnenbatterie (documentation)
First occurred: 25. Januar 2024 um 11:27:33 (1 occurrences)
Last logged: 25. Januar 2024 um 11:27:33

hass not set, sensor: 267841

**Comment by weltmeyer** [comment]
Ist nur eine Warnung... Wenn sonst alles klappt, dann kannst ignorieren.
Oder einfach den Logger von Warnung auf Fehler umstellen, dann siehst du diese Meldung(en) auch nicht mehr.
