### ISSUE TITLE
Inverter_ipv2 problem

### ISSUE THREAD

**Issue by gerrit59** [weltmeyer/ha_sonnenbatterie#43]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.sonnenbatterie
Source: custom_components/sonnenbatterie/sensor.py:313
Integration: Sonnenbatterie (documentation)
First occurred: 25. Januar 2024 um 11:27:33 (8 occurrences)
Last logged: 25. Januar 2024 um 11:27:33

'inverter_ipv2' not in inverter/status/ipv2 -> disabled
'inverter_ppv' not in inverter/status/ppv -> disabled
'inverter_ppv2' not in inverter/status/ppv2 -> disabled
'inverter_upv' not in inverter/status/upv -> disabled
'inverter_upv2' not in inverter/status/upv2 -> disabled

**Comment by weltmeyer** [comment]
Moin,
hast du die readme-datei gelesen? ;)
https://github.com/weltmeyer/ha_sonnenbatterie#unusedunavailable-sensors
