### ISSUE TITLE
Representation of the “Systemstatus” sensor

### ISSUE THREAD

**Issue by Tomoene** [weltmeyer/ha_sonnenbatterie#50]
Would it be possible to display the “systemstatus” sensor in the process so that it works like the sunbattery sensor itself. By this I mean the display not as a graphical table, but as a crossbar (like with the solarbattery: charching, discharching) only with OnGrid, etc.
I'm sorry I can't express myself better. But I don't have the technical terms.
I hope you can understand what I mean.

**Comment by RustyDust** [comment]
> [...] I hope you can understand what I mean.

Unfortunately no. What exactly is it that you want? A textual representation for **all** of the values returned by the `status` API or a special representation of the `systemstatus` sensor? Do you have an example image of what you have in mind?

**Comment by Tomoene** [comment]
I'm sorry I can't express myself better. I would like the sensor "systemstatus" to be displayed as seen here: 

![Screenshot_20240305_135510_Home Assistant](https://github.com/weltmeyer/ha_sonnenbatterie/assets/111224693/1a02e50d-1ebf-4d39-b04e-5a691f63cc9b)

**Comment by RustyDust** [comment]
@Tomoene 
As you may have noticed I labelled this as a bug because in fact what you requested should have been the standard way of operation anyway ;) This should be fixed with the next update. Thanks again!
