### ISSUE TITLE
Question :: How to connect to Sonnen unit

### ISSUE THREAD

**Issue by Infeconex** [weltmeyer/ha_sonnenbatterie#52]
Hi. This is a question, not an issue. How does this custom component connect to the Sonnen unit? Is this over modbus, serial or over IP? My hope is this is over IP, if so - do the Sonnen units have ethernet interfaces, or WiFi client connectivity built in? I'm asking as I may be connecting to one in the coming weeks. and want to prepare any equipment like WiFi to Ethernet bridges, or Serial2USB adaptors.

**Comment by RustyDust** [comment]
> Hi. This is a question, not an issue. How does this custom component connect to the Sonnen unit? Is this over modbus, serial or over IP? 

IP, the SonneBatterie exposes an API to the local network to which it connects to using a wired (cable) connection.
