### ISSUE TITLE
Sensors Stop waorking and values freeze

### ISSUE THREAD

**Issue by doncuco** [weltmeyer/ha_sonnenbatterie#58]
Hello,
since a few weeks my sensors regularly stop working and freeze. I need to reload the integration or restart HASS to fix it.
Any idea where this comes from? And how can I fix this?
Can I provide you any Information that?

Thanks for your help!

And should we better speak in German?

**Comment by RustyDust** [comment]
Gibt's da auch ein Log von HomeAssistant dazu, das wäre hilfreich.
