### ISSUE TITLE
Some meters report a value of `undefined` when their actual value is `0`

### ISSUE THREAD

**Issue by RustyDust** [weltmeyer/ha_sonnenbatterie#59]
@Xitee1 Since the update I'm seeing these meters report `undefined` when their actual value should be `0`:

- `meter_production_a_l1`
- `meter_production_a_l2`
- `meter_production_a_l3`
- `meter_production_w_l1`
- `meter_production_w_l2`
- `meter_production_w_l3`
- '`meter_production_w_total`

To me this looks like a division by zero error somewhere in the code but I can't find any logs to that effect. 

![Bildschirmfoto 2024-05-21 um 08 47 30](https://github.com/weltmeyer/ha_sonnenbatterie/assets/1085162/27de5f5a-727d-4216-a989-3e7ed4c35f09)

**Comment by Xitee1** [comment]
Probably `is not None` needs to be appended to this check
https://github.com/weltmeyer/ha_sonnenbatterie/blob/22483c9c398fd5e51b85ec7d3648ce34ee17352a/custom_components/sonnenbatterie/sensor_list.py#L70
I'll try it tonight.

**Comment by RustyDust** [comment]
I'd rather try

```python
    else 0
```
[here](https://github.com/weltmeyer/ha_sonnenbatterie/blob/22483c9c398fd5e51b85ec7d3648ce34ee17352a/custom_components/sonnenbatterie/sensor_list.py#L75)

'cause I think the `None` is what causes the `undefined` result.

**Comment by Xitee1** [comment]
But then if the value is actually `None` for whatever reason, the sensor will still be set to `0` (and created if it does not exist).
Because the powermeters are a hardcoded list, there is a possibility that they are just not supported. With `else 0` they will still be created in HA, which they will not if we return `None` if the reported value is equal `None`.

**Comment by RustyDust** [comment]
Try running

``` python
print("bla") if (val := 0) else print("blubb")
```

;)

**Comment by Xitee1** [comment]
```python
>>> print(val if (val := 0) else 0)
0
>>> print(val if (val := None) else 0)
0
```
...which means that if the val is `None` (if e.g. the sensor is not supported), `0` will be reported instead of None, which is wrong.

This is what we want:
```python
>>> print(val if (val := 0) is not None else None)
0
>>> print(val if (val := None) is not None else None)
None
```

**Comment by RustyDust** [comment]
Ah, sorry. I skimmed over your initial statement about the possibility of those meters not being supported. I have yet to find a system that doesn't but if there are this is definitely the cleaner solution.

**Comment by Xitee1** [comment]
Hat jetzt leider doch etwas länger gedauert, hab jetzt aber gerade den PR erstellt.

**Comment by RustyDust** [comment]
NP, bin auch nicht dazu gekommen
