### ISSUE TITLE
Energy new at HA 2021.8

### ISSUE THREAD

**Issue by Jelleverley** [weltmeyer/ha_sonnenbatterie#6]
Hi,
I have installed the latest version of HA 2021.8
Unfortunately, the sonnebatterie data is not recognized by HA as power management.
Is it possible that the integration was not designed for this?

Update: I found what the entity needs to be availible in Energy :
state_class: measurement
last_reset: 1970-01-01T00:00:00+00:00
unit_of_measurement: kWh
device_class: energy

**Comment by weltmeyer** [comment]
Hi  Jelleverley,
as this integration only measures Power (Watts) and not Energy(WattHours) it wont ever show up in the energy dashboard :)

What you can do/what i have done is to use the power sensors to a rieman integral sensor (https://www.home-assistant.io/integrations/integration/)

Example for consumption(Creates sensor for ConsumptionEnergy named "PowerConsumption" with unit kWh and usable in energy-dashboard:
` - platform: integration
   source: sensor.sonnenbatterie_XXXXXX_meter_consumption_4_2_w_total
   name: PowerConsumption
   unit_prefix: k`

**Comment by Jelleverley** [comment]
Ok, i'v done it the same way whit the integration
