### ISSUE TITLE
Error on latest HA

### ISSUE THREAD

**Issue by GimpArm** [weltmeyer/ha_sonnenbatterie#62]
Three is an error while starting the integration leaving many entities as undefined that has previously worked.
HA Version 2024.8.2

```
Error while setting up sonnenbatterie platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sonnenbatterie/sensor.py", line 77, in async_setup_entry
    for description in generate_powermeter_sensors(_coordinator=coordinator)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonnenbatterie/sensor_list.py", line 43, in generate_powermeter_sensors
    f"meter_{meter['direction']}_{meter['deviceid']}_{meter['channel']}".lower()
             ~~~~~^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by weltmeyer** [comment]
Hmm i cant reproduce this error.
Did you try to restart to check if the error persists?
Can you access you battery via web-gui?

It seems like the get_powermeter function did result in a string, which is strange

**Comment by GimpArm** [comment]
Yes the web ui works and I've restarted multiple time. Other values are properly updated, like battery charge state and consumption. It seems everything related to power production and the inverter are undefined.

**Comment by weltmeyer** [comment]
So.. as of today  i get the same error without updating HA. But my battery got an update.. Now i can check what is wrong :)

**Comment by weltmeyer** [comment]
Okay. they changed the result from the powermeters from a json array to a json dictionary.
Also they changed the deviceId's of the sensors.

I can work around the dictionary, but if u used any of the values, the ID's have changed.
for me as an example  
"sonnenbatterie_107700_meter_production_4_1_w_l3" changed to 
"sonnenbatterie_107700_meter_production_0_1_w_l3"

as the deviceId move to 0 instead of 4

**Comment by GimpArm** [comment]
Yep, working now, thank you!
