### ISSUE TITLE
Not all sensors available in new HA installation

### ISSUE THREAD

**Issue by dl9bdi** [weltmeyer/ha_sonnenbatterie#63]
I did a new installation of HA in order to move to a docker version. Right now both installations are running in parallel. On the older installation Sonnenbatterie integration still shows a lot of sensor values (abt. 60) The new installation only shows about 10 values.
Values unavailable on the new installation are still shown on the exiting one. 
Connectivity to the battery is given as some values are available.
Regarding the logfile, all values should be available (don't be irritated, I anonomized some of the values in log)

Any idea would be appreciated.

Best Regards
Matthias

![Existing_HA_Installation](https://github.com/user-attachments/assets/becd7d53-0ba7-4030-acbe-b75228754de0)
![New_HA_Installation](https://github.com/user-attachments/assets/4c70b51d-0484-4466-9cd8-89f8b724eba1)
[home-assistant_sonnenbatterie_2024-08-23T13-39-17.897Z.log](https://github.com/user-attachments/files/16729597/home-assistant_sonnenbatterie_2024-08-23T13-39-17.897Z.log)

**Comment by weltmeyer** [comment]
Are the values existing in the Diagnosis area? 
![image](https://github.com/user-attachments/assets/9f34bb28-7335-4994-bc60-d37ef5bf7581)

**Comment by dl9bdi** [comment]
Solved it: was error 40.
Most of the sensors were deactivated and I had to activate them one by one. Now it works.
I think when I installed it the first time several months ago most of them were already activated.

Anyway, thanks a lot for that quick response.
