### ISSUE TITLE
Entities have diapered

### ISSUE THREAD

**Issue by steuerlexi** [weltmeyer/ha_sonnenbatterie#64]
Hello!

Since yesterday, August 26th at 14:40 CEST, a significant number of entities have become unavailable, which has resulted in them no longer updating as expected. This issue has persisted since that time, affecting the functionality and data flow of these entities. The attached screenshot provides a visual reference of the impacted entities and highlights the disruption. 

<img width="379" alt="image" src="https://github.com/user-attachments/assets/1f92c19b-db62-43de-9c4f-59e9039b9e8f">

**Comment by weltmeyer** [comment]
Same as #63 
Try updating the integration and check the sensor IDs. They need to be enabled again via their configuration and the IDs have changed.

**Comment by steuerlexi** [comment]
Thank you @weltmeyer I haven´t seen the #63 ticket. I know have an update offered by HACS and now it looks fine.
