### ISSUE TITLE
Sonnenbatterie API changed

### ISSUE THREAD

**Issue by Thalli5000** [weltmeyer/ha_sonnenbatterie#68]
Hello,

around august I have noticed that something went wrong with the values provided in my energy dashboard. So I took a look at the issues reported for this integration. Quickly I found this topic https://github.com/weltmeyer/ha_sonnenbatterie/issues/65.

But the provided solutions does not solved the issue - in my opinion.

I found out that sonnen changed its API and there are only 10 entities provided and for

- Consumption
- Grid in/out
- Charging
- production

there is now just one entity. Means: Grid and charging is negative while consuming energy from it.

I thought it would help to change the helper, but after that I had the same values vor grid in/grid out and for Charging/discharging.... that's weird isn't it?

Best regards
Steffen

**Comment by RustyDust** [comment]
Can you please check [this](https://github.com/weltmeyer/ha_sonnenbatterie/issues/65#issuecomment-2348451609) and come back with the results?

**Comment by RustyDust** [comment]
Ok, so your battery provides all the states that are queried by the ha_sonnenbatterie integration.
Therefore it seems likely that your entities just got disabled somehow. Can you check the output of "Settings -> Devices & Services -> Sonnebatterie" for the number of entities and maybe provide a screenshot? Also when clicking on either the entities link under the list of sonnebatterie devices or the quick link on the left side, what do you see? Again, a screenshot would be nice.

**Comment by Thalli5000** [comment]
Yes, you are right. there are plenty of entities which have been disabled. 

I just have one entity "Netz Import" enabled, but there is no data coming in.

Screenshots:

![image](https://github.com/user-attachments/assets/cf0a0662-69e6-4222-81fe-013a63efff61)
![image](https://github.com/user-attachments/assets/e129a224-1923-4003-85b6-56aa9a3d7e35)
![image](https://github.com/user-attachments/assets/e75d119a-e434-4c87-805d-caa460f17548)

**Comment by RustyDust** [comment]
The solution seems simple then: just enable all the disabled entities you want/need.

**Comment by Thalli5000** [comment]
holy cow. shame on me. thank you for your support and sorry for the circumstances

**Comment by whiteman7** [comment]
> holy cow. shame on me. thank you for your support and sorry for the circumstances

@Thalli5000 
Hi, I saw on your screenshot the inactive entities, so meter procuction_w... You wrote that you were able to activate them. Are you still getting production data (not consumption data) today?

**Comment by RustyDust** [comment]
> @Thalli5000 Hi, I saw on your screenshot the inactive entities, so meter procuction_w... You wrote that you were able to activate them. Are you still getting production data (not consumption data) today?

Would you please kindly refrain from taking over other people's tickets and instead either add to the original one with new information or open a new issue for your specific problem.
