### ISSUE TITLE
Deprecated config_entry

### ISSUE THREAD

**Issue by Prythi** [weltmeyer/ha_sonnenbatterie#69]
Hi,

Just got a log on a deprecated config:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 8:28:16 PM (1 occurrences)
Last logged: 8:28:16 PM

Detected that custom integration 'sonnenbatterie' sets option flow config_entry explicitly, which is deprecated at custom_components/sonnenbatterie/config_flow.py, line 98: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'sonnenbatterie' custom integration

**Comment by RustyDust** [comment]
Can you give a bit more information about:
- HA version used
- Python version used

**Comment by Prythi** [comment]
HA version: 

2024.12.1 core
2024.11.4 supervisor
14.0 OS

Python:

Not sure? Thought this was managed by the HAOS core.

This is an existing installation. Been using it for 4 or so months now...
