### ISSUE TITLE
Integrate with HA energy

### ISSUE THREAD

**Issue by dowermyr** [weltmeyer/ha_sonnenbatterie#7]
Hi!
Would like to have this integrated:

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by dowermyr** [comment]
I was just about to link the same thing :) +1 on that

**Comment by johanschelin** [comment]
I would also live this to be done!

**Comment by marcorizzi** [comment]
why this request has been closed ? I would like to understand if this is something feasible, hard to implement or whatever

**Comment by weltmeyer** [comment]
> why this request has been closed ? I would like to understand if this is something feasible, hard to implement or whatever

you dont need to open/reopen multiple issues. Energy Dashboard uses Energy, Sonnen provides Power Sensors
